---
- name: Update, upgrade, and reboot all hosts
  hosts: all
  become: true
  tasks:

    - name: Update apt cache
      ansible.builtin.apt:
        update_cache: yes

    - name: Upgrade all packages
      ansible.builtin.apt:
        upgrade: dist
        autoremove: yes

    - name: Reboot if needed
      ansible.builtin.reboot:
        reboot_timeout: 600
        pre_reboot_delay: 10
        post_reboot_delay: 30
