version: "3"
services:
  dns-server:
    container_name: dns-server
    hostname: dns-server
    image: technitium/dns-server:latest
    ports:
       - "5380:5380/tcp" # Web-Dashboard (HTTP)
       - "53:53/udp" 
       - "53:53/tcp" 
    environment:
      - DNS_SERVER_DOMAIN= # Domain Name of DNS-Server 
      - DNS_SERVER_ADMIN_PASSWORD= # Password
    volumes:
      - ./data:/etc/dns
    restart: unless-stopped
    sysctls:
      - net.ipv4.ip_local_port_range=1024 65000
